//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBNW.Dataflow
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "dataflow";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Dataflow";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"NBNW";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DataflowDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DataflowCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DataflowExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DataflowCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDataflowExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DataflowCommandSetId), 0x0001);
	
		// Package identifier
		public const string DataflowPackageId = "50f94825-4600-4c67-b8ec-e2ecd18a1068";
		
		// Editor factory identifier
		public const string DataflowEditorFactoryId = "c02231ea-cb07-4d4f-867c-2de0329a7f43";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DataflowModelExplorerToolWindowId = "84664f78-ffc9-4666-9775-d74f7296bc49";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace NBNW.Dataflow
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DataflowCommandSetId = "c93a48c2-68e7-44a0-ad0d-087d20c181a4";
	}
}